### ISSUE TITLE
Crashing due to "NewConnectionError...[Errno 101] Network is unreachable'))"

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/disputable-values-monitor#117]
This is an error that I've seen a couple times now. The DVM will error out with the traceback attached. (see log attached)
[DVM error log.txt](https://github.com/tellor-io/disputable-values-monitor/files/11081533/DVM.error.log.txt)

telliot versions:
telliot-core 0.2.2
telliot-feeds 0.1.7

DVM version/commit hash: c36a1fdbda7f384c5ee1bb89dd548029568bdb1e

**Comment by tallywiesenberg** [comment]
Closed with #124
