### ISSUE TITLE
Make datafeed lookup programmatic

### ISSUE THREAD

**Issue by oraclown** [tellor-io/disputable-values-monitor#125]
Why? So it doesn't have to be updated in two places every time we officially support a new data type.
Current implementation [here](https://github.com/tellor-io/disputable-values-monitor/blob/main/src/tellor_disputables/__init__.py#L11)
Proposed enhancement pseudocode:
A programatic way to u don't have to keep adding more to the mapping..
```py
import telliot_feeds.all_feeds

# get queryid while listening for reported values
qid_of_reported_value = blah
checking_feed = None # used to check if the value is disputable
for feed in all_feeds:
    if qid_if_dispute == feed.query.query_id:
        checking_feed = feed
if feed is None: return # we don't support it
else: # ... check if the value is disputable using checking_feed
```

**Comment by akremstudy** [comment]
I think you can search the catalog by queryId then use the tag, datafeed[tag], to get the feed but I think the above might be more efficient.
