### ISSUE TITLE
Unsuccessful Bad Value Test (no alert sent)

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/disputable-values-monitor#131]
Just submitted a bad value on goerli, and the DVM did not flag it as `Disputable`. 

Start command: poetry run cli -c 10 --wait 30

output from the DVM:
![Screenshot 2023-04-13 at 12 12 24 PM](https://user-images.githubusercontent.com/72078372/231822428-d58163c6-b6db-46b5-81a3-e2a610b10ac6.png)

Version: 55ba75761273df6ea36e8de4191d84cae19a2704

**Comment by tallywiesenberg** [comment]
-c should be a decimal < 1, representing a percentage. if you input 10 for the flag, that represents a 1000% percent confidence threshold. Can you let me know if you can reproduce the bug with `poetry run cli -c 0.10 --wait 30`? Thanks!

**Comment by spuddyminer** [comment]
tested and confirmed working! Thanks @tallywiesenberg 🤙
