### ISSUE TITLE
is_disputable: Build feed from queryData instead of queryId

### ISSUE THREAD

**Issue by tallywiesenberg** [tellor-io/disputable-values-monitor#22]
Currently feed retrieval uses `DATAFEED_LOOKUP` global dict, mapping queryIds to feeds

Would be ideal to decode the queryData instead and use it to build a feed. This will be more maintainable

**Comment by oraclown** [comment]
See decoding query data in `telliot_feeds.cli.commands.query` I think for an example. Maybe make some of that logic into a reusable function & use it here
