### ISSUE TITLE
streamlit dashboard not working

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/disputable-values-monitor#38]
The streamlit dashboard (as featured in the readme's sweet animated .gif) seems to have stopped working after one of the recent pull requests. Hopefully it's an easy fix to get it working again.

**Comment by oraclown** [comment]
I think it was taken out. I forget the reasoning. @tallywiesenberg ?

**Comment by tallywiesenberg** [comment]
Closed with #57
