### ISSUE TITLE
DVM May Not Pick Up all Disputable Values

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/disputable-values-monitor#61]
Tested some bad values today, and the DVM did not believe that they were disputable. No texts were sent or received.

Example Test submission $666 for eth/usd here: `https://goerli.etherscan.io/tx/0xb40f1498d487a9a5ff18cc87f332aa112151190679fe014a107db9b8d42065f1`
(the price of eth/usd today is around $1,200)

dashboard / log output: 
`|  6 | 1668616008 | https://goerli.etherscan.io/tx/0xb4... | ETH | USD |   666    | no ✔️        |`

Version `commit# daa0a2f6b033700cf2182b78ff46a4a0f19335fe`

**Comment by tallywiesenberg** [comment]
Can you post more logs, specifically the part that shows the DVM's estimation of the ETH/USD price using telliot feeds?

**Comment by oraclown** [comment]
> Can you post more logs, specifically the part that shows the DVM's estimation of the ETH/USD price using telliot feeds?

Would be helpful, but you could also reproduce in a test. Mock the value pulled in to be $666 and see if it catches it
