### ISSUE TITLE
Allow for Monitoring New Feeds like ALBT/USD & RAI/USD

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/disputable-values-monitor#71]
Not sure if this would require code changes, or just documentation. 

Request adding or explaining functionality that allows for monitoring price feeds that were not included in Telliot's "query catalog" at the time of the release. Thanks!

**Comment by tallywiesenberg** [comment]
Closing as this is covered by the `-f` flag to build a query id, then monitor only that query id
