### ISSUE TITLE
monitor new contracts

### ISSUE THREAD

**Issue by spuddyminer** [tellor-io/disputable-values-monitor#97]
Installing the DVM installs old versions of telliot-feeds and telliot-core. This means that the new mainnet contracts cannot be monitored by the main branch DVM. Also, the version of telliot-core that telliot feeds requires is different from the version that tellor disputables requires. 

Request that we update the DVM to always use (and be compatible with) the newest versions of telliot-feeds and telliot-core.

**Comment by tallywiesenberg** [comment]
Covered in #99
